# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [12.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checkout do código do projeto para a máquina
      - uses: actions/checkout@v2
        
      # Setup do Node.JS
      - name: Setup Node.js environment
        uses: actions/setup-node@v1.4.3
        with:
          node-version: ${{ matrix.node-version}}
        
      # Instalando as dependências
      - run: npm install
      
      # Executar os testes usando cucumber
      - run: npm run cy:run:cucumber
      
      # Gera o Relatório em HTML
      - run: npm run report:cucumber
      
      # Publicar relatório em HTML
      - name: Deploy to GithubPages
        uses: JamesIves/github-pages-deploy-action@3.6.2
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: cypress/reports
